import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Header from "@/layout/Header/Header";
import Navigation from "@/components/navi/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="jp">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <Navigation />
        <div className={`${styles.body_container}`}>{children}</div>
      </body>
    </html>
  );
}
