import type { Metadata } from "next";
import styles from "./page.module.css";
import Header from "@/layout/Header/Header";
import "@mantine/core/styles.css";

import "@mantine/dates/styles.css";
import "dayjs/locale/ja";
import { fetchUserProfile } from "@/lib/api/auth/profile";
import { UserInfo } from "@/types";

export const metadata: Metadata = {
  title: "読書かんり",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const user: UserInfo | undefined = await fetchUserProfile();
  return (
    <div>
      <Header userInfo={user} />
      <div className={`${styles.body_container}`}>{children}</div>
    </div>
  );
}
